In [5]:
import numpy as np

In [6]:
# create an array

x = np.array([34,56,21,67,89])

In [7]:
x

array([34, 56, 21, 67, 89])

In [8]:
y = np.array([34,56,21,67,89,70.00])

In [9]:
y

array([34., 56., 21., 67., 89., 70.])

In [10]:
y = np.array([34,56,21,67,89,70.00, 'Aditya'])

In [11]:
y

array(['34', '56', '21', '67', '89', '70.0', 'Aditya'], dtype='<U32')

In [14]:
%%timeit
a = [34,56,21,67,89,70.00,9,'aditya']

53.9 ns ± 3.48 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [15]:
%%timeit
y = np.array([34,56,21,67,89,70.00,9,'aditya'])

1.95 µs ± 127 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
y = np.array([34,56,21,67,89,70])

In [17]:
y.shape

(6,)

In [18]:
y / 2

array([17. , 28. , 10.5, 33.5, 44.5, 35. ])

In [19]:
# arange

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [22]:
np.arange(3,10,0.25)

array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 ,
       5.75, 6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25,
       8.5 , 8.75, 9.  , 9.25, 9.5 , 9.75])

In [29]:
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [30]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
y.ndim

2

In [32]:
y.shape

(4, 3)

In [34]:
y.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
y.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
a = np.array([34,56,21,67,89,70])

In [39]:
a[2]

21

In [40]:
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
y[0,1]

2

In [44]:
y[1,1]

5

In [46]:
y[0:2,0:2]

array([[1, 2],
       [4, 5]])